language: rust

rust:
  - stable
  - beta
  - nightly

cache: cargo

notifications:
  email: never

script:
  - RUST_BACKTRACE=1 cargo test -- --test-threads=1
  - RUST_BACKTRACE=1 cargo test --release -- --test-threads=1
