[package]
name = "adragaria-remastered"
version = "0.1.0"
authors = ["squealer"]

[dependencies]
glutin = "*"
gl = "*"
libc = "*"
png = "*"
sfl_parser = { git = "https://github.com/Teascade/slf_parser" }
