[package]
name = "glerminal"
description = "A lightweight OpenGL terminal"
version = "0.1.0"
authors = ["Teascade <teascade@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = []
categories = []
repository = "https://github.com/Teascade/glerminal"
documentation = "https://docs.rs/glerminal"

[badges]
travis-ci = { repository = "Teascade/glerminal", branch = "0.1.0" }

[dependencies]
glutin = "*"
gl = "*"
libc = "*"
png = "*"
regex = "*"
sfl_parser = "*"

[dev-dependencies]
rand = "*"
